#!/bin/bash

# Docker registry credentials
DOCKER_USERNAME="guerdellyeya"
DOCKER_PASSWORD="14026673a"

# Log in to Docker registry
echo "Logging in to Docker registry..."
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
#create my network
docker network create my-buffer-network

# Function to stop and remove the container if it's already running
stop_and_remove_container() {
  container_name=$1
  if [ "$(docker ps -q -f name=$container_name)" ]; then
    echo "Stopping and removing existing container $container_name..."
    docker stop $container_name
    docker rm $container_name
  fi
}

# Pull the latest buffer db image and run the container
stop_and_remove_container "buffer_container"
docker pull guerdellyeya/mysql-buffer:finalversion
echo "Running the new container for guerdellyeya/mysql-buffer:finalversion..."
db_container_name="buffer_container"
docker run --network my-buffer-network -d --name "$db_container_name" -p 3309:3306 guerdellyeya/mysql-buffer:finalversion

# Pull the latest registrationloginfv image and run the container
stop_and_remove_container "registrationlogin_container"
docker pull guerdellyeya/registrationloginfv:finalversion
echo "Running the new container for guerdellyeya/registrationloginfv:finalversion..."
docker run --network my-buffer-network -d --name "registrationlogin_container" -p 8091:8081 -e SPRING_DATASOURCE_URL=jdbc:mysql://$db_container_name:3309/buffer guerdellyeya/registrationloginfv:finalversion

# Pull the latest angular front image and run the container
stop_and_remove_container "angular_buffer_container"
docker pull guerdellyeya/angular-buffer-project:finalversion
echo "Running the new container for guerdellyeya/angular-buffer-project:finalversion..."
docker run --network my-buffer-network -d --name "angular_buffer_container" -p 4201:80 guerdellyeya/angular-buffer-project:finalversion

# Pull the latest csvfv microservice image and run the container
stop_and_remove_container "csvfv_container"
docker pull guerdellyeya/csvfv:finalversion
echo "Running the new container for guerdellyeya/csvfv:finalversion..."
docker run --network my-buffer-network -d --name "csvfv_container" -p 8092:8082 -e SPRING_DATASOURCE_URL=jdbc:mysql://$db_container_name:3309/buffer guerdellyeya/csvfv:finalversion
