#!/bin/bash

# Docker registry credentials
DOCKER_USERNAME="guerdellyeya"
DOCKER_PASSWORD="14026673a"

# Log in to Docker registry
echo "Logging in to Docker registry..."
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
#create my network
docker network create my-buffer-network


# Pull the latest buffer  db image
docker pull guerdellyeya/buffer:latest

# Run a new container for the buffer db image
echo "Running the new container for guerdellyeya/buffer:latest..."
db_container_name="buffer_container"
docker run --network my-buffer-network -d --name "$db_container_name" -p 3309:3306 guerdellyeya/buffer:latest



# Pull the latest registrationloginfv image
docker pull guerdellyeya/registrationloginfv:latest

# Run the Docker command with the extracted container name replacing 'database_name'
docker run --network my-buffer-network -d -p 8091:8081 -e SPRING_DATASOURCE_URL=jdbc:mysql://$db_container_name:3309/buffer guerdellyeya/registrationloginfv:latest



# Pull the latest angular front  image
docker pull guerdellyeya/angular-buffer:latest

# Run a new container for the planning image
echo "Running the new container for guerdellyeya/angular-buffer:latest..."
docker run --network my-buffer-network -d -p 4201:80 guerdellyeya/angular-buffer:latest


# Pull the latest csvfv microservice image image
docker pull guerdellyeya/csvfv:latest

# Run a new container for the csvfv image
echo "Running the new container for guerdellyeya/team:latest..."
docker run --network my-buffer-network -d -p 8092:8082 -e SPRING_DATASOURCE_URL=jdbc:mysql://$db_container_name:3309/buffer guerdellyeya/csvfv:latest

